### PR TITLE
Starting to work on laravel 5 implementation, test addition and more

### PR DESCRIPTION
**Pull request by namelivia**
I'm starting to add not just some L5 stuff but also tests and some other things I see people doing on some other popular Laravel packages. I've already opened the PR for fixing #4 but it **is not finished yet and should not be merged**, I'll keep updating this. Just opened it so you can start taking a look on the diff and making comments if you see something you don't want me to make.
Thanks!

### CODE REVIEW

**Comment by Braunson** [comment]
Any updates on this @namelivia :)

**Comment by namelivia** [comment]
Working on it!

**Comment by namelivia** [comment]
Btw, there is an issue that is speeding down extremely my development process. So I'll ask to see if you have encountered this. I've configured a new laravel project, for using my branch through a vcs repo in the composer.json on my laravel project.
I've done this before and should work, but for some reason my vcs repo seems not to be "linked" to the fatsecret-laravel dependency.
It think this is because the repo name on github and the package name on Packagist differ but I'm not 100% sure.  

Just asking to see if you have already found this and now how to deal with this, I'll keep on trying!
Thanks!

**Comment by Braunson** [comment]
@namelivia I've updated the GitHub repo name to match the packagist name, let me know if that fixes it.

**Comment by namelivia** [comment]
I think the problem may be because the package name on the composer.json file says `braunson/fat-secret`, I think this sould be updated to braunson/fatsecret-laravel and then the package reuploaded to packagist. From what I've read [there are issues with repository renaming and packagist](https://github.com/composer/packagist/issues/47).

**Comment by Braunson** [comment]
@namelivia I've adjusted everything back 2b24114883442ed956edbd29a01a679672b0f8ce

**Comment by namelivia** [comment]
Yes! It works now! Thank you very much!

**Comment by namelivia** [comment]
Sorry! Is this annoying you with notifications every time I make a commit? I will close the PR and reopen it once I'm finished.

**Pull request closed without merging**
